Repository opensearch-project/dashboards-assistant, pull requests merged in 2024-02, with the labels that each got.

#115 add release note
  release-notes/dashboards-assistant.release-notes-2.12.0.0.md
Labels: Skip-Changelog, v2.12.0, backport 2.x

#124 Feat add tooltip for chat window header
  public/components/__tests__/chat_window_header_title.test.tsx
  public/components/chat_window_header_title.tsx
Labels: Skip-Changelog, backport 2.x

#128 Refactor: get root agent id by calling api
  CHANGELOG.md
  GETTING_STARTED_GUIDE.md
  public/plugin.tsx
  server/index.ts
  server/plugin.ts
  server/routes/chat_routes.ts
  server/routes/regenerate.test.ts
  server/routes/send_message.test.ts
  server/services/chat/olly_chat_service.test.ts
  server/services/chat/olly_chat_service.ts
  server/types.ts
  server/utils/constants.ts
Labels: backport 2.x

#130 fix minutes format in conversation history list
  public/tabs/history/__tests__/chat_history_list.test.tsx
  public/tabs/history/chat_history_list.tsx
Labels: Skip-Changelog, backport 2.x

#134 Fix chat window header title text truncate
  public/components/chat_window_header_title.tsx
Labels: Skip-Changelog, backport 2.x

#137 Fix: comply with the field change of agent framework
  CHANGELOG.md
  release-notes/dashboards-assistant.release-notes-2.12.0.0.md
  server/services/storage/agent_framework_storage_service.test.ts
  server/services/storage/agent_framework_storage_service.ts
Labels: backport 2.x, backport 2.12

#53 [Incontext Insights] wrapper component and service
  CHANGELOG.md
  common/types/config.ts
  docs/incontext_insight/component.md
  docs/incontext_insight/registry.md
  docs/incontext_insight/service.md
  public/chat_header_button.test.tsx
  public/chat_header_button.tsx
  public/components/__tests__/incontext_insight.test.tsx
  public/components/incontext_insight/index.scss
  public/components/incontext_insight/index.tsx
  public/contexts/core_context.tsx
  public/index.ts
  public/plugin.tsx
  public/services/__tests__/incontext_insight_registry.test.ts
  public/services/incontext_insight/incontext_insight_provider.ts
  public/services/incontext_insight/incontext_insight_registry.ts
  public/services/incontext_insight/index.ts
  public/services/index.ts
  public/tabs/chat/chat_page_content.test.tsx
  public/tabs/chat/chat_page_content.tsx
  public/tabs/chat/messages/message_bubble.tsx
  public/tabs/chat_window_header.tsx
  public/types.ts
  server/index.ts
  server/plugin.ts
  tsconfig.json
Labels: v2.12.0, backport 2.x, backport 2.12

#147 Downgrade jsdom to 21 fix failed in node 14
  package.json
  yarn.lock
Labels: Skip-Changelog, backport 2.x, backport 2.12

#148 [2.x] Downgrade jsdom to 21 fix failed in node 14
  package.json
  yarn.lock
Labels: Skip-Changelog, backport 2.12
