Repository opensearch-project/dashboards-assistant, pull requests merged in 2024-01, with the labels that each got.

#92 fix: bypass real error info from backend
  server/routes/chat_routes.ts
  server/routes/send_message.test.ts
Labels: enhancement, Skip-Changelog

#90 add missing unit tests
  public/contexts/__tests__/chat_context.test.tsx
  public/tabs/chat/messages/message_content.test.tsx
  public/utils/tests/notebook.test.ts
Labels: Skip-Changelog

#94 feat: some optimization for customized render function
  .github/PULL_REQUEST_TEMPLATE.md
  common/types/chat_saved_object_attributes.ts
  public/chat_header_button.test.tsx
  public/chat_header_button.tsx
  public/components/__snapshots__/agent_framework_traces.test.tsx.snap
  public/contexts/__tests__/chat_context.test.tsx
  public/contexts/chat_context.tsx
  public/hooks/use_chat_actions.test.tsx
  public/index.ts
  public/plugin.tsx
  public/tabs/chat/messages/message_bubble.test.tsx
  public/tabs/chat/messages/message_bubble.tsx
  public/tabs/chat/messages/message_content.test.tsx
  public/tabs/chat/messages/message_content.tsx
  public/types.ts
  public/utils/notebook.ts
  server/parsers/visualization_card_parser.test.ts
  server/parsers/visualization_card_parser.ts
Labels: Skip-Changelog

#97 Refactor: change variables naming under context of Agent Framework
  common/constants/llm.ts
  common/types/chat_saved_object_attributes.ts
  public/chat_header_button.tsx
  public/components/__tests__/chat_window_header_title.test.tsx
  public/components/__tests__/edit_conversation_name_modal.test.tsx
  public/components/chat_window_header_title.tsx
  public/components/edit_conversation_name_modal.tsx
  public/components/feedback_modal.tsx
  public/contexts/__mocks__/core_context.tsx
  public/contexts/__tests__/chat_context.test.tsx
  public/contexts/chat_context.tsx
  public/contexts/core_context.tsx
  public/hooks/__tests__/use_conversations.test.ts
  public/hooks/index.ts
  public/hooks/use_chat_actions.test.tsx
  public/hooks/use_chat_actions.tsx
  public/hooks/use_conversations.ts
  public/hooks/use_feed_back.test.tsx
  public/hooks/use_save_chat.test.tsx
  public/plugin.tsx
  public/services/__tests__/conversation_load_service.test.ts
  public/services/__tests__/conversations_service.test.ts
  public/services/conversation_load_service.ts
  public/services/conversations_service.ts
  public/tabs/__tests__/chat_window_header.test.tsx
  public/tabs/chat/chat_page.test.tsx
  public/tabs/chat/chat_page.tsx
  public/tabs/chat/chat_page_content.test.tsx
  public/tabs/chat/chat_page_content.tsx
  public/tabs/history/__tests__/chat_history_page.test.tsx
  public/tabs/history/__tests__/chat_history_search_list.test.tsx
  public/tabs/history/__tests__/delete_conversation_confirm_modal.test.tsx
  public/tabs/history/chat_history_page.tsx
  public/tabs/history/chat_history_search_list.tsx
  public/tabs/history/delete_conversation_confirm_modal.tsx
  public/types.ts
  server/parsers/basic_input_output_parser.test.ts
  server/routes/chat_routes.test.ts
  server/routes/chat_routes.ts
  server/routes/get_conversation.test.ts
  server/routes/get_conversations.test.ts
  server/routes/regenerate.test.ts
  server/routes/send_message.test.ts
  server/services/chat/chat_service.ts
  server/services/chat/olly_chat_service.test.ts
  server/services/chat/olly_chat_service.ts
  server/services/storage/agent_framework_storage_service.mock.ts
  server/services/storage/agent_framework_storage_service.test.ts
  server/services/storage/agent_framework_storage_service.ts
  server/services/storage/assistant_index_storage_service.ts
  server/services/storage/saved_objects_storage_service.ts
  server/services/storage/storage_service.ts
Labels: Skip-Changelog

#101 feat: change traceId to interactionId
  common/types/chat_saved_object_attributes.ts
  public/chat_flyout.test.tsx
  public/chat_flyout.tsx
  public/chat_header_button.tsx
  public/components/agent_framework_traces.test.tsx
  public/components/agent_framework_traces.tsx
  public/components/agent_framework_traces_flyout_body.test.tsx
  public/components/agent_framework_traces_flyout_body.tsx
  public/components/feedback_modal.tsx
  public/contexts/__tests__/chat_context.test.tsx
  public/contexts/chat_context.tsx
  public/hooks/use_chat_actions.test.tsx
  public/hooks/use_chat_actions.tsx
  public/hooks/use_feed_back.test.tsx
  public/hooks/use_feed_back.tsx
  public/hooks/use_fetch_agentframework_traces.test.ts
  public/hooks/use_fetch_agentframework_traces.ts
  public/tabs/chat/chat_page_content.test.tsx
  public/tabs/chat/chat_page_content.tsx
  server/parsers/basic_input_output_parser.test.ts
  server/parsers/basic_input_output_parser.ts
  server/routes/chat_routes.test.ts
  server/routes/chat_routes.ts
  server/routes/regenerate.test.ts
Labels: Skip-Changelog

#106 feat: refactor memory API url path and fields
  common/types/chat_saved_object_attributes.ts
  common/utils/llm_chat/traces.ts
  public/components/agent_framework_traces.test.tsx
  public/hooks/use_fetch_agentframework_traces.test.ts
  server/routes/chat_routes.test.ts
  server/services/storage/agent_framework_storage_service.test.ts
  server/services/storage/agent_framework_storage_service.ts
  server/utils/format.ts
  server/utils/message_parser_runner.test.ts
Labels: Skip-Changelog, backport 2.x

#104 fix: suggestedAction could be null
  server/parsers/basic_input_output_parser.test.ts
  server/parsers/basic_input_output_parser.ts
Labels: Skip-Changelog, backport 2.x

#105 minor perf and config improvements
  public/chat_header_button.tsx
  server/index.ts
  yarn.lock
Labels: Skip-Changelog, v2.12.0, backport 2.x

#111 test: add dataTestSubj for chat history list item
  public/tabs/history/chat_history_list.tsx
Labels: Skip-Changelog, backport 2.x

#113 fix History button position
  public/tabs/chat_window_header.tsx
Labels: v2.12.0, backport 2.x

#114 Refactor find last methods
  public/hooks/use_chat_actions.tsx
  public/hooks/use_chat_state.tsx
  public/hooks/use_feed_back.tsx
  public/tabs/chat/chat_page_content.tsx
  public/utils/find_last_index.ts
  public/utils/index.ts
  public/utils/tests/find_last_index.test.ts
Labels: Skip-Changelog, backport 2.x

#117 fix assistant divider is too short
  public/index.scss
Labels: Skip-Changelog, v2.12.0, backport 2.x

#119 add fallback for optional account
  public/components/chat_welcome_message.tsx
  public/contexts/chat_context.tsx
  public/hooks/use_save_chat.tsx
  public/tabs/chat/chat_page_content.tsx
  public/utils/notebook.ts
Labels: Skip-Changelog, v2.12.0, backport 2.x
