Repository opensearch-project/dashboards-assistant, pull requests merged in 2024-09, with the labels that each got.

#269 Fix CVE-2024-4067
  CHANGELOG.md
  package.json
  yarn.lock
Labels: backport 2.x, v2.17.0

#268 Expose a general function for agent execution
  CHANGELOG.md
  common/constants/llm.ts
  public/plugin.tsx
  public/services/assistant_client.ts
  public/services/assistant_service.ts
  public/types.ts
  server/plugin.ts
  server/routes/agent_routes.ts
  server/routes/text2viz_routes.ts
  server/services/assistant_client.ts
  server/services/assistant_service.ts
  server/types.ts
Labels: backport 2.x, v2.17.0

#265 feat: added an AI assistant trigger button to query editor
  CHANGELOG.md
  opensearch_dashboards.json
  public/assets/assistant_trigger.svg
  public/components/ui_action_context_menu.tsx
  public/index.scss
  public/plugin.tsx
  public/services/index.ts
  public/text2viz.tsx
  public/types.ts
  public/ui_triggers.ts
Labels: backport 2.x, v2.17.0, backport 2.17

#275 Add release notes for 2.17.0
  release-notes/dashboards-assistant.release-notes-2.17.0.0.md
Labels: Skip-Changelog, backport 2.x, backport 2.17

#264 feat: add new feature to support text to visualization
  CHANGELOG.md
  common/constants/llm.ts
  common/constants/vis_type_nlq.ts
  common/types/config.ts
  opensearch_dashboards.json
  public/components/visualization/editor_panel.tsx
  public/components/visualization/embeddable/nlq_vis_embeddable.ts
  public/components/visualization/embeddable/nlq_vis_embeddable_factory.ts
  public/components/visualization/embeddable/types.ts
  public/components/visualization/text2vega.ts
  public/components/visualization/text2viz.scss
  public/components/visualization/text2viz.tsx
  public/components/visualization/text2viz_empty.tsx
  public/components/visualization/text2viz_loading.tsx
  public/index.scss
  public/plugin.tsx
  public/services/index.ts
  public/text2viz.tsx
  public/types.ts
  public/vis_nlq/saved_object_loader.ts
  public/vis_nlq/types.ts
  server/index.ts
  server/plugin.ts
  server/routes/text2viz_routes.ts
  server/vis_type_nlq/capabilities_provider.ts
  server/vis_type_nlq/saved_object_type.ts
Labels: backport 2.x, v2.17.0

#266 Support insight with RAG
  CHANGELOG.md
  common/constants/llm.ts
  public/assets/shiny_sparkle.svg
  public/assets/sparkle.svg
  public/components/incontext_insight/generate_popover_body.test.tsx
  public/components/incontext_insight/generate_popover_body.tsx
  public/components/incontext_insight/index.scss
  public/components/incontext_insight/index.tsx
  public/types.ts
  server/plugin.ts
  server/routes/get_agent.ts
  server/routes/summary_routes.ts
Labels: backport 2.x

#267 Add assistant capabilities to control rendering components
  CHANGELOG.md
  public/plugin.tsx
  public/text2viz.tsx
  server/capabilities.ts
  server/plugin.ts
Labels: backport 2.x

#291 Format the json files to avoid autocut PRs
  opensearch_dashboards.json
  package.json
Labels: Skip-Changelog, backport 2.x

#299 fix: make input_instruction can be empty string
  server/routes/text2viz_routes.ts
Labels: backport 2.x

#307 feat: expose an API to check if a give agent config name has agent id configured
  CHANGELOG.md
  common/constants/llm.ts
  public/plugin.tsx
  public/services/assistant_client.ts
  public/services/index.ts
  server/routes/agent_routes.ts
  server/routes/get_agent.ts
  server/routes/summary_routes.ts
  server/routes/text2viz_routes.ts
  server/services/assistant_client.ts
  server/services/chat/olly_chat_service.ts
Labels: backport 2.x

#305 [Backport 2.16] Format the json file to avoid autocut PRs
  opensearch_dashboards.json
Labels: Skip-Changelog

#313 feat: use two agents for text2viz
  CHANGELOG.md
  common/constants/llm.ts
  public/components/visualization/source_selector.tsx
  public/services/assistant_client.ts
  server/routes/agent_routes.ts
  server/routes/text2viz_routes.ts
Labels: backport 2.x

#304 Refactor for message action bar and add metrics for alerting summary
  CHANGELOG.md
  opensearch_dashboards.json
  public/components/incontext_insight/generate_popover_body.test.tsx
  public/components/incontext_insight/generate_popover_body.tsx
  public/components/incontext_insight/index.tsx
  public/hooks/use_feed_back.test.tsx
  public/hooks/use_feed_back.tsx
  public/plugin.tsx
  public/tabs/chat/chat_page_content.tsx
  public/tabs/chat/messages/message_action.test.tsx
  public/tabs/chat/messages/message_action.tsx
  public/tabs/chat/messages/message_bubble.test.tsx
  public/tabs/chat/messages/message_bubble.tsx
  public/types.ts
  public/utils/report_metric.ts
Labels: backport 2.x

#321 Pass dataSourceId for alert summary/insight
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.tsx
  public/types.ts
Labels: backport 2.x

#316 feat: support navigating to discover in alerting popover
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.test.tsx
  public/components/incontext_insight/generate_popover_body.tsx
  public/components/incontext_insight/index.tsx
  public/plugin.tsx
  public/utils/alerting.ts
  public/utils/index.ts
  test/jest.config.js
Labels: backport 2.x

#325 fix(t2viz): string escape should only escape `field`
  CHANGELOG.md
  public/components/visualization/text2vega.ts
Labels: backport 2.x

#327 refactor(t2viz): register the AI actions to query controls in discover
  CHANGELOG.md
  common/types/config.ts
  public/components/ui_action_context_menu.tsx
  public/plugin.tsx
  server/index.ts
Labels: backport 2.x

#329 Add release notes for 2.17.1
  release-notes/dashboards-assistant.release-notes-2.17.1.0.md
Labels: Skip-Changelog, backport 2.x, backport 2.17

#330 T2viz ux improvements
  CHANGELOG.md
  common/types/config.ts
  public/components/ui_action_context_menu.tsx
  public/components/visualization/source_selector.tsx
  public/components/visualization/text2vega.ts
  public/components/visualization/text2viz.tsx
  public/plugin.tsx
  public/types.ts
Labels: backport 2.x, t2viz

#312 T2viz UI metrics
  CHANGELOG.md
  public/components/feedback_thumbs.test.tsx
  public/components/feedback_thumbs.tsx
  public/components/visualization/text2vega.ts
  public/components/visualization/text2viz.scss
  public/components/visualization/text2viz.tsx
  public/types.ts
Labels: backport 2.x, t2viz

#335 Fix dynamic uses of i18n
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.tsx
Labels: backport 2.x

#337 fix: fix create index pattern duplicate cases
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.tsx
  public/utils/alerting.ts
Labels: backport 2.x
