Repository opensearch-project/dashboards-assistant, pull requests merged in 2024-03, with the labels that each got.

#162 update query assist guide to use ml-commons config API
  GETTING_STARTED_GUIDE.md
Labels: backport 2.x

#158 change view trace from suggestions to message action bar
  common/types/chat_saved_object_attributes.ts
  public/tabs/chat/chat_page_content.test.tsx
  public/tabs/chat/chat_page_content.tsx
  public/tabs/chat/messages/message_bubble.test.tsx
  public/tabs/chat/messages/message_bubble.tsx
Labels: Skip-Changelog, backport 2.x

#164 Integrate sidecar service
  CHANGELOG.md
  public/chat_flyout.test.tsx
  public/chat_flyout.tsx
  public/chat_header_button.test.tsx
  public/chat_header_button.tsx
  public/components/__snapshots__/sidecar_icon_menu.test.tsx.snap
  public/components/sidecar_icon_menu.test.tsx
  public/components/sidecar_icon_menu.tsx
  public/contexts/chat_context.tsx
  public/index.scss
  public/tabs/__tests__/chat_window_header.test.tsx
  public/tabs/chat/chat_page.tsx
  public/tabs/chat_window_header.tsx
  public/utils/constants.ts
  release-notes/dashboards-assistant.release-notes-2.13.0.0.md
Labels: backport 2.x, v2.13.0

#159 Add workflow to verify binary install into dashboards
  .github/workflows/verify-binary-installation.yml
Labels: backport 2.x, v2.13.0

#172 doc: add release note for adding workflow to verify binary install
  release-notes/dashboards-assistant.release-notes-2.13.0.0.md
Labels: backport 2.x, v2.13.0

#174 Encode id if it is used in request path
  release-notes/dashboards-assistant.release-notes-2.13.0.0.md
  server/services/storage/agent_framework_storage_service.test.ts
  server/services/storage/agent_framework_storage_service.ts
Labels: Skip-Changelog, backport 2.x, v2.13.0, backport 2.13

#178 Bypass response from backend APIs
  server/services/storage/agent_framework_storage_service.test.ts
  server/services/storage/agent_framework_storage_service.ts
Labels: Skip-Changelog, backport 2.x, v2.13.0, backport 2.13
