Repository opensearch-project/dashboards-assistant, pull requests merged in 2024-10, with the labels that each got.

#343 BugFix: [AlertInsight] Remove the cache of insight agent id in node server
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.tsx
  server/routes/summary_routes.ts
Labels: backport 2.x

#345 fix: fix error timefield and add filter for multi same name index pattern
  CHANGELOG.md
  public/utils/alerting.ts
Labels: backport 2.x

#349 feat: take index pattern and user input to t2viz from discover
  CHANGELOG.md
  public/components/visualization/text2viz.tsx
  public/plugin.tsx
Labels: backport 2.x

#354 Hide incompatible index patterns
  CHANGELOG.md
  public/components/visualization/source_selector.tsx
Labels: backport 2.x

#351 Edit viz in a dialog
  CHANGELOG.md
  public/components/visualization/text2vega.ts
  public/components/visualization/text2viz.scss
  public/components/visualization/text2viz.tsx
  public/components/visualization/viz_style_editor.test.tsx
  public/components/visualization/viz_style_editor.tsx
  server/routes/agent_routes.ts
Labels: backport 2.x

#357 Add release notes for 2.18.0
  release-notes/dashboards-assistant.release-notes-2.18.0.0.md
Labels: backport 2.x, v2.18.0

#359 refactor: Update alerting DSL verify mechanism
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.test.tsx
  public/components/incontext_insight/generate_popover_body.tsx
  public/types.ts
  public/utils/alerting.ts
  public/utils/tests/alerting.test.ts
Labels: backport 2.x, v2.18.0

#365 Refactor: refactor contextProvider get to reduce re-fetch
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.tsx
Labels: backport 2.x, backport 2.18

#368 feat: only support visual editor alerts to navigate to discover
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.test.tsx
  public/components/incontext_insight/generate_popover_body.tsx
Labels: backport 2.x, backport 2.18
