Repository opensearch-project/dashboards-assistant, pull requests merged in 2024-07, with the labels that each got.

#219 Add feature flag to control query assistant like features
  common/types/config.ts
  public/plugin.tsx
  public/types.ts
  server/index.ts
Labels: backport 2.x

#218 feat: text to visualization
  CHANGELOG.md
  common/constants/llm.ts
  opensearch_dashboards.json
  public/components/visualization/source_selector.tsx
  public/components/visualization/text2vega.ts
  public/components/visualization/text2viz.scss
  public/components/visualization/text2viz.tsx
  public/components/visualization/text2viz_empty.tsx
  public/components/visualization/text2viz_loading.tsx
  public/plugin.tsx
  public/text2viz.tsx
  public/types.ts
  server/plugin.ts
  server/routes/get_agent.ts
  server/routes/text2viz_routes.ts
  server/services/chat/olly_chat_service.test.ts
  server/services/chat/olly_chat_service.ts
Labels: backport 2.x, v2.16.0, backport 2.16

#231 added savedObjects to requiredPlugins
  opensearch_dashboards.json
Labels: backport 2.x, backport 2.16

#227 add 2.16 release note
  release-notes/dashboards-assistant.release-notes-2.16.0.0.md
Labels: backport 2.x, v2.16.0, backport 2.16

#239 switch to ml_configuration in agent response as backend changed
  CHANGELOG.md
  release-notes/dashboards-assistant.release-notes-2.16.0.0.md
  server/routes/get_agent.ts
Labels: backport 2.x, v2.16.0, backport 2.16

#246 feat: fix unit test ci failure
  public/components/core_visualization.test.tsx
Labels: Skip-Changelog, backport 2.x, backport 2.16

#215 Initial implementation of context aware alert analysis
  CHANGELOG.md
  common/types/chat_saved_object_attributes.ts
  public/chat_header_button.tsx
  public/components/incontext_insight/generate_popover_body.test.tsx
  public/components/incontext_insight/generate_popover_body.tsx
  public/components/incontext_insight/index.scss
  public/components/incontext_insight/index.tsx
  public/plugin.tsx
  public/services/__tests__/incontext_insight_registry.test.ts
  public/services/incontext_insight/incontext_insight_registry.ts
  public/services/index.ts
  public/types.ts
  public/utils/constants.ts
  server/routes/chat_routes.ts
  server/services/chat/olly_chat_service.ts
Labels: backport 2.x, v2.17.0
