Repository opensearch-project/dashboards-assistant, pull requests merged in 2025-03, with the labels that each got.

#484 Manual backport 474 to 2.x
  package.json
  yarn.lock
Labels: Skip-Changelog

#481 Make sure conversation id been updated before send message
  CHANGELOG.md
  public/chat_header_button.test.tsx
  public/chat_header_button.tsx
Labels: backport 2.x

#482 Fix bug regarding alert summary pop up
  CHANGELOG.md
  public/components/incontext_insight/index.tsx
Labels: backport main

#504 Fix alert summary message action position when no discover button
  public/components/incontext_insight/generate_popover_body.tsx
  public/components/incontext_insight/index.scss
Labels: Skip-Changelog

#506 Change the background color, button position and text for alert summary popover
  public/components/incontext_insight/generate_popover_body.test.tsx
  public/components/incontext_insight/generate_popover_body.tsx
  public/components/incontext_insight/index.scss
  public/components/incontext_insight/index.tsx
  public/tabs/chat/messages/message_action.tsx
  release-notes/dashboards-assistant.release-notes-3.0.0.0-alpha1.md
Labels: Skip-Changelog, v3.0.0-alpha1

#511 chatbot dock bottom border top
  public/chat_flyout.tsx
  public/index.scss
Labels: Skip-Changelog

#512 update the no aggregation PPL error message
  public/utils/pipeline/text_to_ppl_task.ts
  release-notes/dashboards-assistant.release-notes-3.0.0.0-alpha1.md
Labels: Skip-Changelog, v3.0.0-alpha1

#523 Render Icon based on the chat status (enabled or not)
  CHANGELOG.md
  public/components/visualization/text2viz.tsx
Labels: v3.0.0-beta1
