Repository opensearch-project/dashboards-assistant, pull requests merged in 2025-04, with the labels that each got.

#527 Fix failed UTs with OSD 3.0
  .github/workflows/unit_test_workflow.yml
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.tsx
  public/utils/alerting.ts
Labels: v3.0.0-beta1

#531 Move changelog to 3.0.0.0-beta1 release notes
  CHANGELOG.md
  release-notes/dashboards-assistant.release-notes-3.0.0.0-beta1.md
Labels: v3.0.0-beta1

#529 refactor incontext style, add white logo and remove outdated code
  common/types/config.ts
  public/components/incontext_insight/index.scss
  public/components/incontext_insight/index.tsx
  public/services/index.ts
  release-notes/dashboards-assistant.release-notes-3.0.0.0-beta1.md
Labels: Skip-Changelog

#530 Add scroll load conversations
  common/types/chat_saved_object_attributes.ts
  public/hooks/use_chat_actions.tsx
  public/hooks/use_chat_state.tsx
  public/services/conversation_load_service.ts
  public/tabs/chat/chat_page.tsx
  public/tabs/chat/chat_page_content.test.tsx
  public/tabs/chat/chat_page_content.tsx
  public/tabs/history/__tests__/chat_history_list.test.tsx
  public/tabs/history/chat_history_list.tsx
  public/types.ts
  release-notes/dashboards-assistant.release-notes-3.0.0.0-beta1.md
  server/routes/chat_routes.ts
Labels: Skip-Changelog, v3.0.0-beta1

#541 fix query assistant menu disappear due to upstream method signature change
  public/plugin.tsx
  release-notes/dashboards-assistant.release-notes-3.0.0.0-beta1.md
Labels: Skip-Changelog, v3.0.0-beta1

#540 Change chatbot entry point to a single button
  public/chat_header_button.test.tsx
  public/chat_header_button.tsx
  release-notes/dashboards-assistant.release-notes-3.0.0.0-beta1.md
Labels: Skip-Changelog, v3.0.0-beta1

#493 Support streaming output
  common/types/chat_saved_object_attributes.ts
  common/utils/stream/serializer.test.ts
  common/utils/stream/serializer.ts
  common/utils/stream/stream_to_observable.test.ts
  common/utils/stream/stream_to_observable.ts
  package.json
  public/chat_header_button.test.tsx
  public/components/blink_cursor.scss
  public/components/blink_cursor.tsx
  public/components/markdown_with_blink_cursor.test.tsx
  public/components/markdown_with_blink_cursor.tsx
  public/hooks/use_chat_actions.test.tsx
  public/hooks/use_chat_actions.tsx
  public/hooks/use_chat_state.test.tsx
  public/hooks/use_chat_state.tsx
  public/hooks/use_get_chunks_from_http_response.test.tsx
  public/hooks/use_get_chunks_from_http_response.tsx
  public/tabs/chat/chat_page.tsx
  public/tabs/chat/chat_page_content.tsx
  public/tabs/chat/messages/message_content.tsx
  public/utils/message_content_puller.test.ts
  public/utils/message_content_puller.ts
  release-notes/dashboards-assistant.release-notes-3.0.0.0-beta1.md
  server/routes/chat_routes.ts
  server/services/chat/chat_service.ts
  yarn.lock
Labels: Skip-Changelog, v3.0.0-beta1

#542 Fix .plugins-ml-memory-meta not found when get conversations
  release-notes/dashboards-assistant.release-notes-3.0.0.0-beta1.md
  server/routes/chat_routes.ts
  server/routes/get_conversations.test.ts
Labels: Skip-Changelog, v3.0.0-beta1

#547 Fix empty codecov report in CI
  .github/workflows/unit_test_workflow.yml
  codecov.yml
  release-notes/dashboards-assistant.release-notes-3.0.0.0-beta1.md
Labels: Skip-Changelog

#548 log error body or message instead of the entire error object
  CHANGELOG.md
  server/routes/error_handler.test.ts
  server/routes/error_handler.ts
Labels: v3.0.0

#549 [Enhancement] Buffer for special characters when streaming
  CHANGELOG.md
  public/hooks/use_get_chunks_from_http_response.test.tsx
  public/hooks/use_get_chunks_from_http_response.tsx
  public/utils/message_content_puller.test.ts
  public/utils/message_content_puller.ts
Labels: v3.0.0, backport 3.0

#553 Save chatbot flyout visualize state to local storage
  CHANGELOG.md
  public/chat_header_button.test.tsx
  public/chat_header_button.tsx
  public/plugin.tsx
  public/services/index.ts
  public/utils/persisted_chatbot_state.test.ts
  public/utils/persisted_chatbot_state.ts
Labels: v3.0.0, backport 3.0

#545 Improve the chatbot UX by scroll the user input message to the top after sending
  CHANGELOG.md
  public/tabs/chat/chat_page_content.test.tsx
  public/tabs/chat/chat_page_content.tsx
  public/tabs/chat/loading_placeholder.test.tsx
  public/tabs/chat/loading_placeholder.tsx
  public/tabs/chat/messages/message_bubble.tsx
Labels: v3.0.0, backport 3.0

#563 Upgrade derek-ho/start-opensearch to v6 and set java version to 21 for OS 3.0
  .github/workflows/verify-binary-installation.yml
  CHANGELOG.md
Labels: v3.0.0, backport 3.0

#561 Revert "[Backport 3.0] [Enhancement] Buffer for special characters when streaming"
  public/hooks/use_get_chunks_from_http_response.test.tsx
  public/hooks/use_get_chunks_from_http_response.tsx
  public/utils/message_content_puller.test.ts
  public/utils/message_content_puller.ts
Labels: Skip-Changelog

#539 style single metric in text2vis
  release-notes/dashboards-assistant.release-notes-3.0.0.0-beta1.md
  server/routes/text2viz_routes.ts
  server/utils/style_single_metric.test.ts
  server/utils/style_single_metric.ts
Labels: Skip-Changelog

#566 Add 3.0.0.0 release notes
  CHANGELOG.md
  release-notes/dashboards-assistant.release-notes-3.0.0.0.md
Labels: v3.0.0, backport 3.0
