Repository opensearch-project/dashboards-assistant, pull requests merged in 2025-01, with the labels that each got.

#384 return 404 instead of 500 for missing agent config name
  CHANGELOG.md
  server/routes/agent_routes.test.ts
  server/routes/agent_routes.ts
  server/routes/error_handler.test.ts
  server/routes/error_handler.ts
  server/routes/errors.ts
  server/routes/get_agent.ts
  server/routes/summary_routes.test.ts
  server/routes/summary_routes.ts
  server/routes/text2viz_routes.test.ts
  server/routes/text2viz_routes.ts
  server/services/chat/olly_chat_service.test.ts
Labels: backport 2.x

#392 Update UI for In-context summarization in Alerts table
  CHANGELOG.md
  public/assets/sparkle_with_gradient.svg
  public/components/incontext_insight/index.scss
  public/components/incontext_insight/index.tsx
Labels: backport 2.x, v2.19.0

#399 Fix chatbot flyout not show after re-mount
  CHANGELOG.md
  public/chat_header_button.test.tsx
  public/chat_header_button.tsx
Labels: backport 2.x, v2.19.0

#401 feat: Set logo config in assistant and read logo by config
  CHANGELOG.md
  common/types/config.ts
  public/chat_header_button.test.tsx
  public/chat_header_button.tsx
  public/components/incontext_insight/generate_popover_body.tsx
  public/components/incontext_insight/index.tsx
  public/components/visualization/text2viz.tsx
  public/services/index.ts
  public/tabs/__tests__/chat_window_header.test.tsx
  public/tabs/chat/messages/message_bubble.test.tsx
  public/tabs/chat/messages/message_bubble.tsx
  public/tabs/chat_window_header.tsx
Labels: backport 2.x

#395 Add query assistant summary switch to the assistant dropdown list
  CHANGELOG.md
  opensearch_dashboards.json
  public/components/ui_action_context_menu.tsx
  public/plugin.tsx
  public/types.ts
Labels: backport 2.x

#396 Chatbot entry UI redesign
  CHANGELOG.md
  public/chat_header_button.test.tsx
  public/chat_header_button.tsx
  public/index.scss
  public/plugin.tsx
Labels: backport 2.x, v2.19.0

#407 Update dropdown list button label and remove popover title
  CHANGELOG.md
  public/components/ui_action_context_menu.tsx
Labels: backport 2.x, v2.19.0

#410 Disable the rename conversation api using feature flag
  CHANGELOG.md
  common/types/config.ts
  public/components/__tests__/chat_window_header_title.test.tsx
  public/components/__tests__/edit_conversation_name_modal.test.tsx
  public/components/chat_window_header_title.tsx
  public/components/edit_conversation_name_modal.tsx
  public/tabs/history/__tests__/chat_history_list.test.tsx
  public/tabs/history/__tests__/chat_history_page.test.tsx
  public/tabs/history/__tests__/chat_history_search_list.test.tsx
  public/tabs/history/chat_history_list.tsx
  test/config_schema_mock.ts
Labels: backport 2.x, v2.19.0

#409 Use feature flag to disable the delete conversation api
  CHANGELOG.md
  common/types/config.ts
  public/components/__tests__/chat_window_header_title.test.tsx
  public/components/__tests__/edit_conversation_name_modal.test.tsx
  public/components/edit_conversation_name_modal.tsx
  public/tabs/history/__tests__/chat_history_list.test.tsx
  public/tabs/history/__tests__/chat_history_page.test.tsx
  public/tabs/history/__tests__/chat_history_search_list.test.tsx
  public/tabs/history/chat_history_list.tsx
  test/config_schema_mock.ts
Labels: backport 2.x, v2.19.0

#398 feat: incorporate dynamic config service when reading chat.enabled flag
  CHANGELOG.md
  public/plugin.tsx
  server/capabilities.ts
  server/plugin.ts
Labels: backport 2.x, v2.19.0

#418 [CVE-2024-21538] Bump cross-spawn from 6.0.5 and 7.0.3 to 7.0.5
  package.json
  yarn.lock
Labels: Skip-Changelog, backport 2.x, v2.19.0, backport 2.19
