Repository opensearch-project/dashboards-assistant, pull requests merged in 2025-02, with the labels that each got.

#421 [CVE-2024-21538] Bump cross-spawn from 7.0.3 to 7.0.5
  package.json
  yarn.lock
Labels: Skip-Changelog, backport 2.x, v2.19.0, backport 2.19

#426 doc: add release notes for 2.19
  release-notes/dashboards-assistant.release-notes-2.19.0.0.md
Labels: backport 2.x, backport 2.19

#432 cleanup CHANGELOG & release-notes
  CHANGELOG.md
  release-notes/dashboards-assistant.release-notes-2.19.0.0.md
Labels: backport 2.x

#429 500 error if workspace is invalid
  CHANGELOG.md
  package.json
  server/routes/error_handler.ts
  server/routes/summary_routes.ts
Labels: backport 2.x

#438 add flag to control if display conversation list
  CHANGELOG.md
  common/types/config.ts
  public/tabs/__tests__/chat_window_header.test.tsx
  public/tabs/chat_window_header.tsx
  test/config_schema_mock.ts
Labels: backport 2.x

#435 Update chatbot UI to align with new look
  CHANGELOG.md
  public/index.scss
  public/tabs/chat/chat_page_content.tsx
  public/tabs/chat/messages/message_bubble.tsx
Labels: backport 2.x

#452 remove os_insight agent
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.tsx
  server/routes/summary_routes.test.ts
  server/routes/summary_routes.ts
Labels: backport 2.x

#436 postprocessing data2summary prompt
  CHANGELOG.md
  server/routes/summary_routes.test.ts
  server/routes/summary_routes.ts
Labels: backport 2.x

#458 fix unhandled exception when workspace id not exists
  CHANGELOG.md
  server/routes/summary_routes.ts
Labels: backport 2.x

#468 remove dompurify and use the one from OSD
  package.json
  yarn.lock
Labels: Skip-Changelog, backport 2.19

#474 add dompurify back
  package.json
  yarn.lock
Labels: backport 2.19

#472 Add fallback logic for index type detection
  CHANGELOG.md
  server/routes/index_type_detect.test.tsx
  server/routes/index_type_detect.tsx
Labels: backport 2.x

#473 fix insight api response
  CHANGELOG.md
  server/routes/summary_routes.ts
Labels: backport 2.x

#467 Adjust footer buttons padding inside alert in-context insight popover panel
  CHANGELOG.md
  public/components/incontext_insight/generate_popover_body.tsx
  public/tabs/chat/messages/message_action.tsx
Labels: backport 2.x
